# Generated by Django 3.1.5 on 2021-01-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('description_markdown', models.TextField(blank=True)),
                ('author', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
