# Generated by Django 3.1.5 on 2021-01-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='mrjsaw', max_length=80),
            preserve_default=False,
        ),
    ]
